# Generated by Django 5.0.6 on 2024-07-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misdatos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cacrrito',
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
