# Generated by Django 5.0.6 on 2024-07-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misdatos', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
