# Generated by Django 5.0.6 on 2024-07-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misdatos', '0004_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('bebida', models.CharField(max_length=100)),
                ('tamano', models.CharField(max_length=50)),
                ('extras', models.TextField(blank=True)),
            ],
        ),
    ]
